FROM golang:1.23-alpine AS builder

WORKDIR /usr/src/golang

COPY ./go.mod .
COPY main.go .

RUN go mod download && go mod verify
RUN go build -v -o /usr/local/bin/golang ./...

FROM scratch

COPY --from=builder /usr/local/bin/golang /usr/local/bin/golang

CMD ["/usr/local/bin/golang"]

#docker build -t diegopctba/golang-fullcycle -f Dockerfile.prod .
